import { BadRequestException, Injectable, NotFoundException } from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';
@Injectable() export class CommerceService { constructor(private readonly prisma:PrismaService){}
 private money(n:number){return Math.round((n+Number.EPSILON)*100)/100}
 private invoiceNo(prefix:string){const d=new Date(); const date=`${d.getFullYear()}${String(d.getMonth()+1).padStart(2,'0')}${String(d.getDate()).padStart(2,'0')}`; return `${prefix}-${date}-${Math.random().toString(36).slice(2,7).toUpperCase()}`}
 async createPurchase(b:string,d:any){if(!Array.isArray(d.items)||!d.items.length)throw new BadRequestException('At least one item is required'); return this.prisma.$transaction(async tx=>{let sub=0,tax=0; const items:any[]=[]; for(const i of d.items){const p=await tx.product.findFirst({where:{id:i.productId,businessId:b}}); if(!p)throw new NotFoundException('Product not found'); const q=Number(i.quantity),cost=Number(i.unitCost),rate=Number(i.taxRate??p.taxRate); const line=this.money(q*cost); sub+=line; tax+=this.money(line*rate/100); items.push({productId:p.id,quantity:q,unitCost:cost,taxRate:rate,lineTotal:line});} const total=this.money(sub+tax); const number=`PUR-${Date.now()}-${Math.random().toString(36).slice(2,5).toUpperCase()}`; const purchase=await tx.purchase.create({data:{businessId:b,supplierId:d.supplierId||null,purchaseNumber:number,subtotal:sub,taxTotal:tax,grandTotal:total,items:{create:items}}}); for(const i of items){const inv=await tx.inventory.upsert({where:{productId:i.productId},update:{quantity:{increment:i.quantity}},create:{businessId:b,productId:i.productId,quantity:i.quantity}}); await tx.stockMovement.create({data:{businessId:b,productId:i.productId,type:'PURCHASE_IN',quantity:i.quantity,reference:`purchase:${purchase.id}`}}); void inv;} await tx.cashEntry.create({data:{businessId:b,direction:'OUTGOING',amount:total,source:'PURCHASE',referenceId:purchase.id}}); return tx.purchase.findUnique({where:{id:purchase.id},include:{items:true,supplier:true}});})}
 async createSale(b:string,d:any){if(!Array.isArray(d.items)||!d.items.length)throw new BadRequestException('At least one item is required'); return this.prisma.$transaction(async tx=>{const business=await tx.business.findUnique({where:{id:b}}); if(!business)throw new NotFoundException('Business not found'); let sub=0,tax=0,items:any[]=[]; for(const i of d.items){const p=await tx.product.findFirst({where:{id:i.productId,businessId:b}}); if(!p)throw new NotFoundException('Product not found'); const inv=await tx.inventory.findUnique({where:{productId:p.id}}); const q=Number(i.quantity),price=Number(i.unitPrice??p.sellingPrice),disc=Number(i.discount??0),rate=Number(i.taxRate??p.taxRate); if(Number(inv?.quantity||0)<q)throw new BadRequestException(`Insufficient stock for ${p.name}`); const line=this.money(q*price-disc); sub+=line; tax+=this.money(line*rate/100); items.push({productId:p.id,quantity:q,unitPrice:price,discount:disc,taxRate:rate,lineTotal:line}); }
 const total=this.money(sub+tax); const sale=await tx.sale.create({data:{businessId:b,customerId:d.customerId||null,status:'CONFIRMED',subtotal:sub,discount:d.discount??0,taxTotal:tax,grandTotal:total,items:{create:items}}}); for(const i of items){await tx.inventory.update({where:{productId:i.productId},data:{quantity:{decrement:i.quantity}}}); await tx.stockMovement.create({data:{businessId:b,productId:i.productId,type:'SALE_OUT',quantity:i.quantity,reference:`sale:${sale.id}`}});} const place=d.placeOfSupply||business.state||null; const same=!!place && !!business.state && place.toLowerCase()===business.state.toLowerCase(); const cgst=same?this.money(tax/2):0, sgst=same?this.money(tax-cgst):0, igst=same?0:tax; const inv=await tx.invoice.create({data:{businessId:b,saleId:sale.id,customerId:d.customerId||null,invoiceNumber:this.invoiceNo(business.invoicePrefix),status:'ISSUED',subtotal:sub,cgst,sgst,igst,taxTotal:tax,grandTotal:total,amountDue:total,placeOfSupply:place,issuedAt:new Date(),items:{create:items.map(i=>({productId:i.productId,quantity:i.quantity,unitPrice:i.unitPrice,taxRate:i.taxRate,lineTotal:i.lineTotal}))}}}); return {sale,invoice:inv};})}
 listSales(b:string){return this.prisma.sale.findMany({where:{businessId:b},include:{customer:true,items:{include:{product:true}},invoice:true},orderBy:{createdAt:'desc'}})}
 listInvoices(b:string){return this.prisma.invoice.findMany({where:{businessId:b},include:{customer:true,payments:true,items:{include:{product:true}}},orderBy:{createdAt:'desc'}})}
 async addPayment(b:string,d:any){const amount=Number(d.amount); if(amount<=0)throw new BadRequestException('Amount must be positive'); return this.prisma.$transaction(async tx=>{if(d.invoiceId){const inv=await tx.invoice.findFirst({where:{id:d.invoiceId,businessId:b}});if(!inv)throw new NotFoundException('Invoice not found');const due=Number(inv.amountDue);if(amount>due)throw new BadRequestException('Payment exceeds invoice due');const paid=Number(inv.amountPaid)+amount;const newDue=this.money(Number(inv.grandTotal)-paid);const status=newDue<=0?'PAID':'PARTIALLY_PAID';const payment=await tx.payment.create({data:{businessId:b,invoiceId:inv.id,customerId:inv.customerId||null,direction:'INCOMING',method:d.method||'CASH',amount,notes:d.notes}});await tx.invoice.update({where:{id:inv.id},data:{amountPaid:paid,amountDue:newDue,status}});await tx.cashEntry.create({data:{businessId:b,direction:'INCOMING',amount,source:'PAYMENT',referenceId:payment.id}});return payment;} const payment=await tx.payment.create({data:{businessId:b,customerId:d.customerId||null,supplierId:d.supplierId||null,direction:d.direction||'INCOMING',method:d.method||'CASH',amount,notes:d.notes}});await tx.cashEntry.create({data:{businessId:b,direction:d.direction||'INCOMING',amount,source:'PAYMENT',referenceId:payment.id}});return payment;})}
}
