import type { SupabaseClient } from "@supabase/supabase-js";

/**
 * Pulls a compact, real snapshot of the business's current numbers.
 * This is the ONLY source of numbers the AI is allowed to talk about.
 * Nothing here is generated by the model — it is all queried straight
 * from Postgres via the same RPC functions the dashboard/reports use.
 */
export async function buildBusinessSnapshot(supabase: SupabaseClient, businessId: string) {
  const today = new Date();
  const toISO = (d: Date) => d.toISOString().slice(0, 10);
  const monthStart = toISO(new Date(Date.UTC(today.getUTCFullYear(), today.getUTCMonth(), 1)));
  const todayStr = toISO(today);
  const sevenDaysAgo = new Date(today);
  sevenDaysAgo.setUTCDate(sevenDaysAgo.getUTCDate() - 6);

  const [todaySummary, monthSummary, weekSales, customerDue, stock, expenseBreakdown] = await Promise.all([
    supabase.rpc("dashboard_summary", { p_business_id: businessId, p_start: todayStr, p_end: todayStr }).maybeSingle(),
    supabase.rpc("dashboard_summary", { p_business_id: businessId, p_start: monthStart, p_end: todayStr }).maybeSingle(),
    supabase.rpc("report_sales", { p_business_id: businessId, p_start: toISO(sevenDaysAgo), p_end: todayStr }),
    supabase.rpc("report_customer_due", { p_business_id: businessId }),
    supabase.rpc("report_stock", { p_business_id: businessId }),
    supabase.rpc("report_expenses", { p_business_id: businessId, p_start: monthStart, p_end: todayStr }),
  ]);

  const lowStock = (stock.data || []).filter((p: any) => p.is_low);
  const dueList = customerDue.data || [];

  return {
    as_of: today.toISOString(),
    today: todaySummary.data || {},
    this_month: monthSummary.data || {},
    last_7_days_sales: weekSales.data || [],
    customers_who_owe_money: dueList.slice(0, 15),
    total_customers_with_due: dueList.length,
    low_stock_products: lowStock,
    expense_breakdown_this_month: expenseBreakdown.data || [],
  };
}

export function buildSystemPrompt(snapshot: unknown): string {
  return [
    "You are the AI Business Assistant inside BusinessOS Cloud AI, talking to a small shop or business owner.",
    "You must answer ONLY using the JSON business data provided below. This data is real, pulled live from the owner's own database.",
    "STRICT RULES:",
    "1. Never invent, estimate, or guess any number that is not present in the data below.",
    "2. If the data needed to answer isn't in the snapshot, say plainly that you don't have that information yet, instead of guessing.",
    "3. Keep answers short, plain, and practical — the owner is not an accountant. Avoid jargon like 'accounts receivable'; say 'customer due' instead.",
    "4. When asked 'what should I focus on', base it only on the low stock list and the customers who owe money in the data.",
    "5. Always state amounts exactly as given in the data (do not round differently or convert currency).",
    "",
    "BUSINESS DATA SNAPSHOT (JSON):",
    JSON.stringify(snapshot, null, 2),
  ].join("\n");
}
